_target_: lerobot.common.robot_devices.robots.boris.BorisRobot
robot_type: boris

cameras:
  wrist:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: /dev/hello-nav-head-camera # TODO: ajustar aqui para o id da camera no robô real
    fps: 10
    width: 1280
    height: 720
    rotation: -90
  head:
    _target_: lerobot.common.robot_devices.cameras.intelrealsense.IntelRealSenseCamera.init_from_name
    name: Intel RealSense D435I
    fps: 30
    width: 640
    height: 480
    rotation: 90
